### ISSUE TITLE
Set up flutter

### ISSUE THREAD

**Issue by Theasal** [patryk1999/DECO7381#2]

**Comment by shreyas-kamat** [comment]
Download the [Flutter SDK](https://docs.flutter.dev/get-started/install), extract the ZIP and add the file location to your Path, then run `flutter doctor` in the command line and see if you've fulfil all the requirements.

**Comment by shreyas-kamat** [comment]
Then, you can follow [THIS](https://codelabs.developers.google.com/codelabs/flutter-codelab-first#0) guide by Google Developers
